kind: Service
apiVersion: v1
metadata:
  name: shoppingcart
  labels:
    run: shoppingcart
spec:
  type: LoadBalancer
  selector:
    run: shoppingcart
  ports:
    - protocol: TCP
      port: 80
      name: http