kind: Service
apiVersion: v1
metadata:
  name: shoppingcart
  labels:
    app: shoppingcart
spec:
  type: LoadBalancer
  selector:
    app: shoppingcart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000